# Generated by Django 4.2 on 2023-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('rank', models.CharField(max_length=10)),
                ('market_cap', models.CharField(max_length=200)),
            ],
        ),
    ]
